spring.application.name=my-portfolio

server.port=9999

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Db connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

#Goggle
spring.security.oauth2.client.registration.google.client-id=${GOGGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOGGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email